name: Maven build

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  mvn:
    uses: netcracker/qubership-core-infra/.github/workflows/maven-build-with-sonar.yaml@v1.0.9
    with:
      event-name: ${{ github.event_name }}
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      upload-artifact: true
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  docker-build:
    needs: [mvn]
    uses: netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@v1.0.9
    with:
      dry-run: false
