name: Verify on pull requests

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  mvn:
    uses: netcracker/qubership-core-infra/.github/workflows/run-maven-with-sonar.yaml@v1.0.0
    with:
      maven-goal: verify
      java-version: 21
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
